#!/bin/bash
if [ "$check" -le "2" ]
then
        echo 4294967298 > /sys/module/zfs/parameters/zfs_arc_sys_free
        if [ $(free -m | awk '{print $4}' | head -2 | tail -1) -le 3072 ]
        then
                sync
                echo 3 > /proc/sys/vm/drop_caches
                echo 'clear cache'
        fi
fi
